title:        PSAS
tagline:      Rockets
description:  Rockets
canonical:    http://psas.pdx.edu
url:          ''

# Owner/author information
owner:
  name:           Portland State Aerpospace Society
  avatar:         avatar.png
  bio:            "Rockets"
  email:          info@psas.pdx.edu
  twitter:        pdxaerospace
  github:         psas
  location:       "Portland, Ore"

exclude: ['Makefile', 'README.markdown', 'assets/less',
    'assets/vendor/bootstrap',
    'assets/vendor/jssor/bower.json',
    'assets/vendor/jssor/demos-jquery',
    'assets/vendor/jssor/demos-no-jquery',
    'assets/vendor/jssor/examples-jquery',
    'assets/vendor/jssor/examples-no-jquery',
    'assets/vendor/jssor/img',
    'assets/vendor/jssor/skin',
    'assets/vendor/jssor/tool',
    'assets/vendor/jssor/transition-builder',
    'assets/vendor/jssor/transitions',
    'assets/vendor/jssor/README.md',
    'assets/vendor/jssor/readme.txt',
]

timezone:    America/Los_Angeles
future:      true
highlighter: pygments
markdown:    kramdown

sass:
    style: :compressed

# Links to include in top navigation
# For external links add external: true
links:
  - title: Rockets
    url: /rockets/
  - title: Launches
    url: /launches/
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
